import base64
from functools import lru_cache
from pathlib import Path
from typing import cast

from pydantic import AliasChoices, Field, model_validator
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=str(Path(__file__).resolve().parents[2] / ".env"),
        env_file_encoding="utf-8",
        extra="ignore",
    )

    app_name: str = Field(default="Start On API", alias="APP_NAME")
    app_version: str = Field(default="0.1.0", alias="APP_VERSION")
    environment: str = Field(default="development", alias="APP_ENV")
    log_level: str = Field(default="INFO", alias="LOG_LEVEL")
    api_host: str = Field(default="0.0.0.0", alias="API_HOST")
    api_port: int = Field(
        default=8000,
        alias="API_PORT",
        validation_alias=AliasChoices("API_PORT", "PORT"),
    )
    api_reload: bool = Field(default=False, alias="API_RELOAD")
    api_v1_prefix: str = Field(default="/api/v1", alias="API_V1_PREFIX")
    web_cors_allowed_origins: str = Field(
        default="",
        alias="WEB_CORS_ALLOWED_ORIGINS",
    )
    app_description: str = Field(
        default=(
            "FastAPI backend for Start On. "
            "Provides health checks, quest generation, OCR text extraction, "
            "Notion sync, and placeholder profile/stat endpoints."
        ),
        alias="APP_DESCRIPTION",
    )
    supabase_url: str | None = Field(default=None, alias="SUPABASE_URL")
    supabase_service_role_key: str | None = Field(
        default=None,
        alias="SUPABASE_SERVICE_ROLE_KEY",
    )
    supabase_anon_key: str | None = Field(default=None, alias="SUPABASE_ANON_KEY")
    gemini_api_key: str | None = Field(default=None, alias="GEMINI_API_KEY")
    gemini_model_name: str = Field(
        default="gemini-3.5-flash",
        alias="GEMINI_MODEL_NAME",
    )
    gemini_max_output_tokens: int = Field(
        default=2048,
        ge=256,
        le=8192,
        alias="GEMINI_MAX_OUTPUT_TOKENS",
    )
    gemini_thinking_level: str | None = Field(
        default="low",
        alias="GEMINI_THINKING_LEVEL",
    )
    notion_token_encryption_key: str | None = Field(
        default=None,
        alias="NOTION_TOKEN_ENCRYPTION_KEY",
    )

    @model_validator(mode="after")
    def validate_required_external_service_settings(self) -> "Settings":
        required_values = {
            "SUPABASE_URL": self.supabase_url,
            "SUPABASE_SERVICE_ROLE_KEY": self.supabase_service_role_key,
            "SUPABASE_ANON_KEY": self.supabase_anon_key,
            "NOTION_TOKEN_ENCRYPTION_KEY": self.notion_token_encryption_key,
        }
        missing_fields = [
            field_name
            for field_name, value in required_values.items()
            if not isinstance(value, str) or not value.strip()
        ]

        if missing_fields:
            missing_values = ", ".join(missing_fields)
            raise ValueError(
                "Missing required environment variables: "
                f"{missing_values}. Check backend/.env or your deployment secrets.",
            )

        if not _is_valid_fernet_key(self.notion_token_encryption_key):
            raise ValueError(
                "NOTION_TOKEN_ENCRYPTION_KEY must be a valid Fernet key "
                "(URL-safe base64-encoded 32-byte key), such as one generated by "
                "cryptography.fernet.Fernet.generate_key().",
            )

        return self

    @property
    def cors_allowed_origins(self) -> list[str]:
        return [
            origin
            for origin in (
                item.strip()
                for item in self.web_cors_allowed_origins.split(",")
            )
            if origin
        ]


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    return Settings()


class _LazySettings:
    def __getattr__(self, name: str) -> object:
        return getattr(get_settings(), name)


settings = cast(Settings, _LazySettings())


def _is_valid_fernet_key(value: str | None) -> bool:
    if not isinstance(value, str):
        return False

    normalized = value.strip()
    if not normalized:
        return False

    try:
        decoded = base64.urlsafe_b64decode(normalized.encode("ascii"))
    except (ValueError, UnicodeEncodeError):
        return False
    return len(decoded) == 32
